name: unit_tests

on: [ pull_request, push ] 

jobs:
  Unit-test:
    name: Run unit tests in master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 1.11 }
      - name: Run tests
        run: ./gradlew test
